language: go

os:
- linux
- osx
- windows

addons:
  apt:
    packages:
    - ninja-build=1.7.1-1~ubuntu16.04.1
    - pkg-config
    sources:
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe
  homebrew:
    packages:
    - ninja
    - ccache

go:  
- "1.12.x"

cache: ccache

before_script: 
- go get -d -v
- ( cd $(go list -f '{{ .Dir }}' github.com/libgit2/git2go) && $OLDPWD/prepare.sh )

script: 
- make test
- env CGO_ENABLED=1 go build --tags "static" -ldflags "-extldflags '-static'" .
