deploy:
  api_key:
    secure: YdM/HjLuNXXgJu4M1Vc66yORh4BeOP36D+jLy3sbE3h4c00QyCV8NEmmJOCjH/c+YZsJsESmvdSxhKxFcaRHvWslUyV9LiG6H0xRXJAsd295aBC7KVPOJEyoNcIKDT02Axh9y5DRIH3Jk4jI6lxVkU5m4ewR8LWwrkXQS1lGTDLrtrGB1ymmbmjKmxbM/ZkyVS98cPB/QKA+P6GxO2KkQzfJ8ExfEa/SOWUxxytSa14Brypd3RHIVsCmQUcgZEEsChUdQsddPLDe8tgKFMnOvWF6U+B9yoltMU99g61sdiLBMS4MSRViivSmPZCUEmzukasCwPP0jzZ1KfZGP2YLy+WBDBGCl0Qs6lz2/ItSSqW24K+60duKox9QiGqMObXBvorMo/07n1Liao6SP1RYM6eghmObviplxth8LEruVR1AHRYCrbPTU0z6RV1r+5MLTzilIUB5ZyU6OCBr8siLjvomdvss0+dYXUQa2bBLcWwb3dnrTEUy8Bjv9WHSOKM2QwmTF52RsLV5LHIRBw2rQVMa+VVvDBzpzCqmtCgUYxeOw4/rb8T0sPeRQFX2vMi58kdwBdXOjxbBF/x1LIIVGcM8WVY58x3XnVXgxU3irFqUcT5tSKk7f0LIm+CVKijmEoBMs8jwmShJZyHkGp7MwHPB3lrphN/gn3bHeJDepZ4=
  file: "$RELEASE_FILE"
  name: "0x${TRAVIS_COMMIT}"
  prerelease: true
  provider: releases
  skip_cleanup: true
  on:
    all_branches: true

language: go

os:
- linux
- osx
- windows

dist: xenial

env: RELEASE_FILE=gitql-$TRAVIS_OS_NAME.tar

addons:
  apt:
    packages:
    - ninja-build
    - pkg-config
  homebrew:
    packages:
    - ninja
    - ccache

go:
- "1.12.x"

cache: ccache

before_script:
- choco install -y make cmake ninja || ( brew update && brew install ninja ccache ) || true
- bash prepare.sh

script:
- cp -v "$(go list -f '{{ .Target }}' github.com/navigaid/gitql)" $TRAVIS_BUILD_DIR
- tar cf $RELEASE_FILE gitql
