language: go

os:
- linux
- osx
- windows

dist: xenial

addons:
  apt:
    packages:
    - ninja-build
    - pkg-config
  homebrew:
    packages:
    - ninja
    - ccache

go:  
- "1.12.x"

cache: ccache

before_script: 
- choco install -y make cmake ninja || true
- go get -d -v
- ( cd $(go list -f '{{ .Dir }}' github.com/libgit2/git2go) && $OLDPWD/prepare.sh )

script: 
- env CGO_ENABLED=1 go build --tags "static" -ldflags "-extldflags '-static'" .
