name: CI
on: 
  push:
    branches:
    - master
  pull_request: 
    branches:
    - master
jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cloudson/gitql
    
    - name: Run tests
      run: | 
        make test
    
    - name: Build linux
      env:
        GOPATH: /home/runner/work/cloudson/go
        TARGET_OS_ARCH: linux/amd64
      run: | 
        make build
        ./gitql -v
    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: gitql-linux64
        path: ./gitql

  build-mac:
    name: Build mac
    runs-on: macOS-10.14
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cloudson/gitql
    
    - name: Run tests
      run: | 
        make test

    - name: Build mac
      env:
        TARGET_OS_ARCH: darwin/amd64
      run: | 
        brew install pkg-config
        export PKG_CONFIG_PATH=${PWD}/libgit2/install/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(PWD)/libgit2/install/lib
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$(PWD)/libgit2/install/lib
        make build-dynamic || true
        ./gitql -v
    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: gitql-mac64
        path: ./gitql

  build-windows:
    name: Build windows
    runs-on: windows-2019
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Run tests
      run: | 
        make test

    - name: Build windows
      env:
        TARGET_OS_ARCH: windows/amd64
      run: | 
        choco install ninja vcredist2017
        make build
        .\gitql.exe -v

    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: gitql-win64
        path: .\gitql.exe