name: CI
on: 
  push:
    branches:
    - master
  pull_request: 
    branches:
    - master
jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cloudson/gitql
    
    - name: Run tests
      run: | 
        go test -v ./... 
    
    - name: Build linux
      run: | 
        go build . 
        ./gitql -v
    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: gitql-linux64
        path: ./gitql

  build-mac:
    name: Build mac
    runs-on: macOS-10.15
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cloudson/gitql
    
    - name: Run tests
      run: | 
        go test -v ./... 

    - name: Build mac
      run: | 
        go build .
        ./gitql -v
    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: gitql-mac64
        path: ./gitql

  build-windows:
    name: Build windows
    runs-on: windows-2019
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Run tests
      run: | 
        go test -v ./... 

    - name: Build windows
      run: | 
        go build .
        .\gitql.exe -v

    - uses: actions/upload-artifact@master
      name: Generating artifact
      with:
        name: gitql-win64
        path: .\gitql.exe