name: CI
on: [push]
jobs:
  build-linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cloudson/gitql
    
    - name: Run tests
      run: | 
        make test
    
    - name: Build linux
      env:
        GOPATH: /home/runner/work/cloudson/go
        TARGET_OS_ARCH: linux/amd64
      run: | 
        make build
        ./gitql -v

  build-mac:
    name: Build mac
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cloudson/gitql
    
    - name: Run tests
      run: | 
        make test

    - name: Build mac
      env:
        TARGET_OS_ARCH: darwin/amd64
      run: | 
        brew install pkg-config
        export PKG_CONFIG_PATH=${PWD}/libgit2/install/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(PWD)/libgit2/install/lib
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$(PWD)/libgit2/install/lib
        make build-dynamic || true
        ./gitql -v